name: Build and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: ci

    env:
        ACR_NAME: ${{ vars.ACR_NAME }}
        REPOSITORY_NAME: ${{ vars.REPOSITORY_NAME }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Docker image
        run: |
          docker build -t $ACR_NAME.azurecr.io/$REPOSITORY_NAME:latest .

      - name: Push to Azure Container Registry
        run: |
          docker push $ACR_NAME.azurecr.io/$REPOSITORY_NAME:latest
