name: Build and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-push-ci:
    runs-on: ubuntu-latest
    environment: ci

    env:
        ACR_NAME: ${{ vars.ACR_NAME }}
        REPOSITORY_NAME: ${{ vars.REPOSITORY_NAME }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Log in to ACR
        run: |
            az acr login --name $ACR_NAME
  

      - name: Build Docker image
        run: |
          docker build -t $ACR_NAME.azurecr.io/$REPOSITORY_NAME:latest .

      - name: Push to Azure Container Registry
        run: |
          docker push $ACR_NAME.azurecr.io/$REPOSITORY_NAME:latest
  deploy-ci:
    runs-on: ubuntu-latest
    environment: ci

    env:
        TF_VAR_subscriptionId: ${{ secrets.SUBSCRIPTIONID }}
        TF_VAR_app_name: ${{ vars.APP_NAME }}
        TF_VAR_env: ${{ vars.ENV }}
        TF_VAR_ecr_repository_name: ${{ vars.ECR_REPOSITORY_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      - name: Initialize Terraform
        run: terraform init infra

      - name: Plan Terraform deployment
        run: terraform plan -out=tfplan infra

#      - name: Apply Terraform changes
#        run: terraform apply -auto-approve tfplan